CREATE TABLE IF NOT EXISTS accounts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(20) NOT NULL,
  firstName VARCHAR(100) NOT NULL,
  lastName VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  passwordHash VARCHAR(255) NOT NULL,
  role ENUM('Admin', 'User') NOT NULL DEFAULT 'User',
  verified DATETIME NULL,
  verificationToken VARCHAR(255) NULL,
  resetToken VARCHAR(255) NULL,
  resetTokenExpires DATETIME NULL,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS refreshTokens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  accountId INT NOT NULL,
  token VARCHAR(500) NOT NULL,
  expires DATETIME NOT NULL,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  createdByIp VARCHAR(100) NULL,
  revoked DATETIME NULL,
  revokedByIp VARCHAR(100) NULL,
  replacedByToken VARCHAR(500) NULL,
  FOREIGN KEY (accountId) REFERENCES accounts(id) ON DELETE CASCADE
);
